export const SET_USER = 'SET_USER'
export const USERS_ERROR = 'USERS_ERROR'
export const LOAD_TRANSACTIONS = 'LOAD_TRANSACTIONS'
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION'
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'

